server:
  port: 8222
eureka:
  client:
    register-with-eureka: false

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/user/**
          filters:
            - AuthenticationFilter
        - id: company
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/company/**
          filters:
            - AuthenticationFilter
        - id: identity
          uri: http://localhost:9898
          predicates:
            - Path=/auth/**