spring:
  application:
    name: identity
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    hikari:
      username: postgres
      password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

application:
  config:
    user-url: localhost:8070/api/v1/user

server:
  port: 9898